import { PrismaClient, Role, OpportunityType } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // seed admin user
  const admin = await prisma.user.upsert({
    where: { email: 'admin@example.com' },
    update: {},
    create: {
      email: 'admin@example.com',
      password: '$2b$10$hashedpassword', // replace with a hashed password in production
      role: Role.ADMIN,
    },
  });

  // Exchanges registry seed data
  const exchanges = [
    {
      name: 'Binance',
      slug: 'binance',
      logoUrl: '/logos/binance.png',
      ccxtId: 'binance',
      regions: ['global'],
      makerFee: 0.001,
      takerFee: 0.001,
      withdrawNetworks: ['ERC20', 'TRC20', 'BEP20'],
      p2pSupported: true,
      p2pAdapter: 'binance',
      scannerConfig: { interval: 10, minSpread: 0.5 },
    },
    {
      name: 'Bybit',
      slug: 'bybit',
      logoUrl: '/logos/bybit.png',
      ccxtId: 'bybit',
      regions: ['global'],
      makerFee: 0.001,
      takerFee: 0.001,
      withdrawNetworks: ['ERC20', 'TRC20'],
      p2pSupported: true,
      p2pAdapter: 'bybit',
      scannerConfig: { interval: 10, minSpread: 0.5 },
    },
    {
      name: 'OKX',
      slug: 'okx',
      logoUrl: '/logos/okx.png',
      ccxtId: 'okx',
      regions: ['global'],
      makerFee: 0.001,
      takerFee: 0.0015,
      withdrawNetworks: ['ERC20', 'TRC20', 'BSC'],
      p2pSupported: true,
      p2pAdapter: 'okx',
      scannerConfig: { interval: 10, minSpread: 0.5 },
    },
    {
      name: 'KuCoin',
      slug: 'kucoin',
      logoUrl: '/logos/kucoin.png',
      ccxtId: 'kucoin',
      regions: ['global'],
      makerFee: 0.001,
      takerFee: 0.001,
      withdrawNetworks: ['ERC20', 'TRC20', 'BSC'],
      p2pSupported: true,
      p2pAdapter: 'kucoin',
      scannerConfig: { interval: 10, minSpread: 0.5 },
    },
    {
      name: 'MEXC',
      slug: 'mexc',
      logoUrl: '/logos/mexc.png',
      ccxtId: 'mexc',
      regions: ['global'],
      makerFee: 0.001,
      takerFee: 0.0015,
      withdrawNetworks: ['ERC20', 'TRC20', 'BSC'],
      p2pSupported: true,
      p2pAdapter: 'mexc',
      scannerConfig: { interval: 10, minSpread: 0.5 },
    },
    {
      name: 'Gate.io',
      slug: 'gateio',
      logoUrl: '/logos/gateio.png',
      ccxtId: 'gateio',
      regions: ['global'],
      makerFee: 0.002,
      takerFee: 0.002,
      withdrawNetworks: ['ERC20', 'TRC20'],
      p2pSupported: false,
      scannerConfig: { interval: 15, minSpread: 0.5 },
    },
    {
      name: 'Bitget',
      slug: 'bitget',
      logoUrl: '/logos/bitget.png',
      ccxtId: 'bitget',
      regions: ['global'],
      makerFee: 0.0008,
      takerFee: 0.001,
      withdrawNetworks: ['ERC20', 'TRC20', 'BSC'],
      p2pSupported: true,
      p2pAdapter: 'bitget',
      scannerConfig: { interval: 10, minSpread: 0.5 },
    },
    {
      name: 'HTX (Huobi)',
      slug: 'htx',
      logoUrl: '/logos/htx.png',
      ccxtId: 'huobi',
      regions: ['global'],
      makerFee: 0.002,
      takerFee: 0.002,
      withdrawNetworks: ['ERC20', 'TRC20'],
      p2pSupported: true,
      p2pAdapter: 'huobi',
      scannerConfig: { interval: 10, minSpread: 0.5 },
    },
    {
      name: 'Kraken',
      slug: 'kraken',
      logoUrl: '/logos/kraken.png',
      ccxtId: 'kraken',
      regions: ['US', 'EU'],
      makerFee: 0.0026,
      takerFee: 0.004,
      withdrawNetworks: ['ERC20'],
      p2pSupported: false,
      scannerConfig: { interval: 15, minSpread: 0.5 },
    },
    {
      name: 'Coinbase',
      slug: 'coinbase',
      logoUrl: '/logos/coinbase.png',
      ccxtId: 'coinbase',
      regions: ['US', 'EU'],
      makerFee: 0.006,
      takerFee: 0.006,
      withdrawNetworks: ['ERC20'],
      p2pSupported: false,
      scannerConfig: { interval: 15, minSpread: 0.5 },
    },
    {
      name: 'Bitfinex',
      slug: 'bitfinex',
      logoUrl: '/logos/bitfinex.png',
      ccxtId: 'bitfinex',
      regions: ['global'],
      makerFee: 0.001,
      takerFee: 0.002,
      withdrawNetworks: ['ERC20'],
      p2pSupported: false,
      scannerConfig: { interval: 15, minSpread: 0.5 },
    },
    {
      name: 'Crypto.com',
      slug: 'cryptocom',
      logoUrl: '/logos/cryptocom.png',
      ccxtId: 'cryptocom',
      regions: ['global'],
      makerFee: 0.004,
      takerFee: 0.004,
      withdrawNetworks: ['ERC20'],
      p2pSupported: false,
      scannerConfig: { interval: 15, minSpread: 0.5 },
    },
    {
      name: 'BingX',
      slug: 'bingx',
      logoUrl: '/logos/bingx.png',
      ccxtId: 'bingx',
      regions: ['global'],
      makerFee: 0.0001,
      takerFee: 0.0003,
      withdrawNetworks: ['ERC20', 'TRC20'],
      p2pSupported: true,
      p2pAdapter: 'bingx',
      scannerConfig: { interval: 10, minSpread: 0.5 },
    },
    {
      name: 'Bitmart',
      slug: 'bitmart',
      logoUrl: '/logos/bitmart.png',
      ccxtId: 'bitmart',
      regions: ['global'],
      makerFee: 0.0025,
      takerFee: 0.0025,
      withdrawNetworks: ['ERC20', 'TRC20'],
      p2pSupported: false,
      scannerConfig: { interval: 15, minSpread: 0.5 },
    },
    {
      name: 'LBank',
      slug: 'lbank',
      logoUrl: '/logos/lbank.png',
      ccxtId: 'lbank',
      regions: ['global'],
      makerFee: 0.001,
      takerFee: 0.001,
      withdrawNetworks: ['ERC20', 'TRC20'],
      p2pSupported: false,
      scannerConfig: { interval: 15, minSpread: 0.5 },
    },
    {
      name: 'CoinEx',
      slug: 'coinex',
      logoUrl: '/logos/coinex.png',
      ccxtId: 'coinex',
      regions: ['global'],
      makerFee: 0.001,
      takerFee: 0.001,
      withdrawNetworks: ['ERC20', 'TRC20'],
      p2pSupported: false,
      scannerConfig: { interval: 15, minSpread: 0.5 },
    },
    {
      name: 'Poloniex',
      slug: 'poloniex',
      logoUrl: '/logos/poloniex.png',
      ccxtId: 'poloniex',
      regions: ['global'],
      makerFee: 0.0015,
      takerFee: 0.0025,
      withdrawNetworks: ['ERC20'],
      p2pSupported: false,
      scannerConfig: { interval: 15, minSpread: 0.5 },
    },
    {
      name: 'WhiteBIT',
      slug: 'whitebit',
      logoUrl: '/logos/whitebit.png',
      ccxtId: 'whitebit',
      regions: ['EU', 'UA'],
      makerFee: 0.001,
      takerFee: 0.001,
      withdrawNetworks: ['ERC20', 'TRC20', 'BSC'],
      p2pSupported: true,
      p2pAdapter: 'whitebit',
      scannerConfig: { interval: 10, minSpread: 0.5 },
    },
    {
      name: 'EXMO',
      slug: 'exmo',
      logoUrl: '/logos/exmo.png',
      ccxtId: 'exmo',
      regions: ['EU', 'UA'],
      makerFee: 0.002,
      takerFee: 0.002,
      withdrawNetworks: ['ERC20'],
      p2pSupported: true,
      p2pAdapter: 'exmo',
      scannerConfig: { interval: 10, minSpread: 0.5 },
    },
    {
      name: 'Phemex',
      slug: 'phemex',
      logoUrl: '/logos/phemex.png',
      ccxtId: 'phemex',
      regions: ['global'],
      makerFee: 0.001,
      takerFee: 0.001,
      withdrawNetworks: ['ERC20', 'TRC20'],
      p2pSupported: false,
      scannerConfig: { interval: 15, minSpread: 0.5 },
    },
  ];

  for (const ex of exchanges) {
    await prisma.exchange.upsert({
      where: { slug: ex.slug },
      update: {},
      create: {
        name: ex.name,
        slug: ex.slug,
        logoUrl: ex.logoUrl,
        ccxtId: ex.ccxtId,
        regions: ex.regions,
        makerFee: ex.makerFee,
        takerFee: ex.takerFee,
        withdrawNetworks: ex.withdrawNetworks,
        p2pSupported: ex.p2pSupported,
        p2pAdapter: ex.p2pAdapter,
        scannerConfig: ex.scannerConfig as any,
      },
    });
  }

  console.log('Seed completed');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });